version = 0.1
[default.deploy.parameters]
stack_name = "cdm-manager-https"
resolve_s3 = true
s3_prefix = "cdm-manager-https"
region = "us-west-2"
profile = "hackathon-participant"
capabilities = "CAPABILITY_IAM"
image_repositories = []
